[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[workspace] 
members = [ "aoc_core", "solutions/year2023"] 

[dependencies]
aoc_core = { path = "aoc_core" }
year2023 = { path = "solutions/year2023" }
